spring.application.name=starwars-api-service
server.port=8080

# Resilience4j Circuit Breaker Config
resilience4j.circuitbreaker.instances.swapi.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.swapi.slidingWindowSize=10
resilience4j.circuitbreaker.instances.swapi.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.swapi.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.swapi.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.swapi.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.swapi.failureRateThreshold=50

# Resilience4j Rate Limiter Config
resilience4j.ratelimiter.instances.swapi.limitForPeriod=5
resilience4j.ratelimiter.instances.swapi.limitRefreshPeriod=10s
resilience4j.ratelimiter.instances.swapi.timeoutDuration=0

# Resilience4j Retry Config
resilience4j.retry.instances.swapi.maxAttempts=3
resilience4j.retry.instances.swapi.waitDuration=2s

# Actuator (to monitor resilience status)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Logging
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{20} - %msg%n
