name: Microservice CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  call-reusable-workflow:
    uses: victorrumanski/my-spring-service/.github/workflows/reusable-ci.yml@main
    with:
      image_name: ${{ github.repository }}
    secrets: inherit
